### ISSUE TITLE
Unable to create charcter

### ISSUE THREAD

**Issue by Cheyron** [duniul/butterlord-tools#1]
I get a "Sorry..." message when trying to download a character I made... https://imgur.com/C8xFXnx

**Comment by duniul** [comment]
Hmm, what error are you getting in the console? My guess would be that it isn't able to download the `WandererStringsLoader.dll` because something is blocking it, or because you are including invalid characters somewhere.

**Comment by Cheyron** [comment]
I will check the console now

**Comment by Cheyron** [comment]
I can't get an error to show in the console but the response header when I download says Status Code: 304. All characters I typed out and were not copy pasted. I am using a US keyboard.

**Comment by Cheyron** [comment]
I don't know what you did but I was just able to download my character and it worked... thanks!
