### ISSUE TITLE
Suggestion?

### ISSUE THREAD

**Issue by danando123** [duniul/butterlord-tools#2]
Would you be doing a Kingdom creator like the butterlord? would be amazing if you do!

**Comment by danando123** [comment]
[KingdomTemplate-611-1-0-1-1587146693.zip](https://github.com/duniul/butterlord-tools/files/4498413/KingdomTemplate-611-1-0-1-1587146693.zip)
Tried to make a mod for a kingdom called Corner dwellers, the game crashes when on splash screen loading after pressing New campaign...

**Comment by duniul** [comment]
Sounds cool like a cool idea, and based on the files it shouldn't be too different to set up!

I'd prefer to keep this small for now though, still working out bugs and issues with companions.

**Comment by danando123** [comment]
cool :)
