### ISSUE TITLE
Problems with the Bannerlord Wanderer Creator

### ISSUE THREAD

**Issue by DiegoLox1** [duniul/butterlord-tools#22]
Hi duniul,

first of all that you very much for your great work 👍 
I would like to create some custom companions however, I always get an error code.  Error ID: 8865786802324b29b86e48f609437d3b
The code always changes but maybe it helps showing it to you.
I would really appreciate your help. Thx

**Comment by Nigkage1** [comment]
Having the same problem. d7580953b9a1414f87f911d97a4bd074

**Comment by duniul** [comment]
Hey, sorry for the very late reply! 🙏 

The site has now been updated to work with Bannerlord 1.1.1.
