### ISSUE TITLE
Problem with the site?

### ISSUE THREAD

**Issue by MaxSteine01** [duniul/butterlord-tools#24]
Hello, I'm getting this error, what can I do about it?
![image](https://user-images.githubusercontent.com/113395707/189773640-c9634715-c9db-4a82-ae94-5f3abd38ba15.png)

**Comment by Mjdecker1234** [comment]
I am getting this too. I think its sadly abandoned.

**Comment by duniul** [comment]
Hey, sorry for the very late reply! 🙏 

The site has now been updated to work with Bannerlord 1.1.1.
